/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Variant({
  'men' : IDL.Null,
  'bridal' : IDL.Null,
  'kids' : IDL.Null,
  'casual' : IDL.Null,
  'women' : IDL.Null,
});
export const ClothingItem = IDL.Record({
  'pattern' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'itemType' : IDL.Text,
  'category' : Category,
  'photo' : IDL.Text,
  'price' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Shop = IDL.Record({
  'clothing' : IDL.Vec(ClothingItem),
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeShops' : IDL.Func([], [], []),
  'addClothingItem' : IDL.Func([IDL.Text, ClothingItem], [], []),
  'attachPhotoToItem' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
  'getItemDetails' : IDL.Func(
      [IDL.Text],
      [ClothingItem, IDL.Vec(Shop)],
      ['query'],
    ),
  'getItemPhoto' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'searchItems' : IDL.Func(
      [
        IDL.Opt(Category),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Vec(ClothingItem)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Variant({
    'men' : IDL.Null,
    'bridal' : IDL.Null,
    'kids' : IDL.Null,
    'casual' : IDL.Null,
    'women' : IDL.Null,
  });
  const ClothingItem = IDL.Record({
    'pattern' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'itemType' : IDL.Text,
    'category' : Category,
    'photo' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Shop = IDL.Record({
    'clothing' : IDL.Vec(ClothingItem),
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeShops' : IDL.Func([], [], []),
    'addClothingItem' : IDL.Func([IDL.Text, ClothingItem], [], []),
    'attachPhotoToItem' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
    'getItemDetails' : IDL.Func(
        [IDL.Text],
        [ClothingItem, IDL.Vec(Shop)],
        ['query'],
      ),
    'getItemPhoto' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'searchItems' : IDL.Func(
        [
          IDL.Opt(Category),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Vec(ClothingItem)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };