/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'men' : null } |
  { 'bridal' : null } |
  { 'kids' : null } |
  { 'casual' : null } |
  { 'women' : null };
export interface ClothingItem {
  'pattern' : string,
  'name' : string,
  'color' : string,
  'itemType' : string,
  'category' : Category,
  'photo' : string,
  'price' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Shop {
  'clothing' : Array<ClothingItem>,
  'name' : string,
  'phone' : string,
  'location' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeShops' : ActorMethod<[], undefined>,
  'addClothingItem' : ActorMethod<[string, ClothingItem], undefined>,
  'attachPhotoToItem' : ActorMethod<[string, ExternalBlob], string>,
  'getItemDetails' : ActorMethod<[string], [ClothingItem, Array<Shop>]>,
  'getItemPhoto' : ActorMethod<[string], [] | [ExternalBlob]>,
  'listCategories' : ActorMethod<[], Array<Category>>,
  'searchItems' : ActorMethod<
    [[] | [Category], [] | [string], [] | [string], [] | [string]],
    Array<ClothingItem>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];